pipeline {

    agent any

    environment {

        AIRFLOW_URL = "http://host.docker.internal:8080/api/v1"

        DAG_ID = "travel_pipeline"

        API_IMAGE = "voyage-api:latest"

        K8S_NAMESPACE = "voyage-analytics"

        K8S_DEPLOYMENT = "voyage-api"

        K8S_SERVICE = "voyage-api-service"
    }

    options {
        timestamps()
        disableConcurrentBuilds()
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Project Information') {

            steps {

                sh '''

                echo "=========================================="
                echo "Voyage Analytics MLOps Pipeline"
                echo "=========================================="

                echo "Workspace : $(pwd)"
                echo "Branch    : ${BRANCH_NAME}"
                echo "Build No  : ${BUILD_NUMBER}"
                echo "Image     : ${API_IMAGE}"

                echo
                docker --version
                git --version
                curl --version | head -1
                jq --version
                kubectl version --client
                minikube version

                '''
            }
        }

        // stage('Verify Kubernetes') {

        //     steps {

        //         sh '''

        //         echo "Current Context"

        //         kubectl config current-context

        //         echo

        //         echo "Cluster Nodes"

        //         kubectl get nodes

        //         '''
        //     }
        // }


        stage('Trigger Airflow DAG') {

            steps {

                script {

                    env.DAG_RUN_ID = sh(

                        script: '''
                        curl -s \
                        -u admin:admin \
                        -H "Content-Type: application/json" \
                        -X POST \
                        ${AIRFLOW_URL}/dags/${DAG_ID}/dagRuns \
                        -d '{}' \
                        | jq -r '.dag_run_id'
                        ''',

                        returnStdout: true

                    ).trim()

                    echo "Triggered DAG Run ID: ${env.DAG_RUN_ID}"
                }
            }
        }


        stage('Wait for DAG Completion') {

            steps {

                script {

                    timeout(time: 30, unit: 'MINUTES') {

                        waitUntil {

                            def status = sh(

                                script: """
                                curl -s \
                                -u admin:admin \
                                ${AIRFLOW_URL}/dags/${DAG_ID}/dagRuns/${env.DAG_RUN_ID} \
                                | jq -r '.state'
                                """,

                                returnStdout: true

                            ).trim()

                            echo "Current DAG State : ${status}"

                            if (status == "success") {
                                return true
                            }

                            if (status == "failed") {
                                error("Airflow DAG Failed")
                            }

                            sleep 20

                            return false
                        }
                    }
                }
            }
        }

        stage('Build Voyage API Image') {

            steps {

                sh '''

                echo "Building Docker Image..."

                docker build \
                    -t ${API_IMAGE} \
                    ./api

                echo
                docker images | grep voyage-api

                '''
            }
        }

        // stage('Deploy to Kubernetes') {

        //     steps {

        //         sh '''

        //         echo "Deploying Kubernetes Resources..."

        //         kubectl apply -f kubernetes/

        //         kubectl rollout status deployment/${K8S_DEPLOYMENT} \
        //         -n ${K8S_NAMESPACE}

        //         '''
        //     }
        // }

        // stage('Verify Deployment') {

        //     steps {

        //         sh '''

        //         echo "Pods"

        //         kubectl get pods \
        //         -n ${K8S_NAMESPACE}

        //         echo

        //         echo "Services"

        //         kubectl get svc \
        //         -n ${K8S_NAMESPACE}

        //         echo

        //         echo "Deployments"

        //         kubectl get deployment \
        //         -n ${K8S_NAMESPACE}

        //         '''
        //     }
        // }

    }

    post {

        success {

            echo "Pipeline Completed Successfully!"

        }

        failure {

            echo "Pipeline Failed!"

        }

        always {

            cleanWs()

        }
    }

}